services:
  odin:
    image: mbround18/odin:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: odin
    volumes:
      - odin-output:/data/odin/target/release
  valheim:
    depends_on:
      - odin
    image: sterim/valheim:latest
    env_file:
      - ./server.env
    build:
      context: .
      dockerfile: ./Dockerfile
      target: valheim
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      # only needed for crossplay
      # - "2458:2458/udp"
    restart: unless-stopped
    volumes:
      - ../mnt/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ../mnt/server:/home/steam/valheim
      - ../mnt/backups:/home/steam/backups
      - ../mnt/odin-output:/home/steam/.odin

volumes:
  odin-output:
