services:
  odin:
    image: mbround18/odin:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: odin
    volumes:
      - odin-output:/data/odin/target/release
  valheim:
    depends_on:
      - odin
    image: sterim/valheim:latest
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - chown
      - fowner
      - dac_override
      - setgid
      - setuid
      - sys_nice
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 250M
    env_file:
      - ../server.env
    build:
      context: .
      dockerfile: ./Dockerfile
      target: valheim
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      # only needed for crossplay
      # - "2458:2458/udp"
      - "127.0.0.1:9001:9001/tcp" # Huginn web interface
    restart: unless-stopped
    volumes:
      - ../mnt/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ../mnt/server:/home/steam/valheim
      - ../mnt/backups:/home/steam/backups
      - ../mnt/odin-output:/home/steam/.odin
    networks:
      - valheim-bifrost

networks:
  valheim-bifrost:
    driver: bridge
    name: valheim-bifrost

volumes:
  odin-output:
